x-odoo-env: &odoo-env
  ODOO_DB_HOST: ${DB_HOST:-db}
  ODOO_DB_PORT: ${DB_PORT:-5432}
  ODOO_DB_USER: ${DB_USER:-odoo}
  ODOO_DB_PASSWORD: ${DB_PASSWORD:-odoo}
  ODOO_LIST_DB: ${ODOO_LIST_DB:-False}
  ODOO_PROXY_MODE: True

x-odoo-defaults: &odoo-defaults
  image: soolit-tech/odoo-community:${ODOO_VERSION:-18}
  volumes:
    - odoo-filestore:/var/lib/odoo

services:
  odoo-production:
    <<: *odoo-defaults
    volumes:
    - odoo-filestore:/var/lib/odoo
    depends_on:
      - db
    environment:
      <<: *odoo-env
      ODOO_DB_ROUTER_RULES: "[{\"match\":\"^([a-z0-9-]+)\\\\.odoo\\\\.localhost$\",\"replace\":\"\\\\1-odoo-production\"},{\"match\":\"^([a-z0-9-]+)\\\\.staging\\\\.odoo\\\\.localhost$\",\"replace\":\"\\\\1-odoo-staging\"}]"
      ODOO_SERVER_WIDE_MODULES: base,web,map_host_to_db
      SERVER_ADDONS_JSON_B64: W3sidXJsIjogImh0dHBzOi8vZ2l0aHViLmNvbS9remhhMC9vZG9vLXNlcnZlci11dGlscy5naXQiLCAiYnJhbmNoIjogbnVsbH1d
    command:
      - >
        setup-util get-addons -j -b "$${SERVER_ADDONS_JSON_B64}"
        && echo "/mnt/extra-addons/odoo-server-utils" >> /home/odoo/odoo-addons.txt
        && ./set-config.sh
        && wait-for-psql
        && odoo
    labels:
      - traefik.enable=true
      - traefik.http.services.odoo.loadbalancer.server.port=8069
      - traefik.http.services.odoo.loadbalancer.healthcheck.path=/web/health
      - traefik.http.services.odoo.loadbalancer.healthcheck.interval=30s
      - traefik.http.services.odoo.loadbalancer.healthcheck.timeout=5s

      - traefik.http.services.odoo-websocket.loadbalancer.server.port=8072
      - traefik.http.services.odoo-websocket.loadbalancer.sticky.cookie=true

      - traefik.http.routers.odoo.rule=HostRegexp(`[a-z0-9-]+\.odoo\.localhost$`)
      - traefik.http.routers.odoo.service=odoo
      - traefik.http.routers.odoo.entrypoints=web
      - traefik.http.routers.odoo.priority=1000

      - traefik.http.routers.odoo-websocket.rule=HostRegexp(`[a-z0-9-]+\.odoo\.localhost$`) && PathPrefix(`/websocket`)
      - traefik.http.routers.odoo-websocket.service=odoo-websocket
      - traefik.http.routers.odoo-websocket.entrypoints=web
      - traefik.http.routers.odoo-websocket.priority=1010

      - traefik.http.routers.odoo-staging.rule=HostRegexp(`[a-z0-9-]+\.staging\.odoo\.localhost$`)
      - traefik.http.routers.odoo-staging.service=odoo
      - traefik.http.routers.odoo-staging.entrypoints=web
      - traefik.http.routers.odoo-staging.priority=100

      - traefik.http.routers.odoo-staging-websocket.rule=HostRegexp(`[a-z0-9-]+\.staging\.odoo\.localhost$`) && PathPrefix(`/websocket`)
      - traefik.http.routers.odoo-staging-websocket.service=odoo-websocket
      - traefik.http.routers.odoo-staging-websocket.entrypoints=web
      - traefik.http.routers.odoo-staging-websocket.priority=110

  db:
    image: postgres:17
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
      POSTGRES_DB: ${POSTGRES_DATABASE:-postgres}
      PGDATA: /var/lib/postgresql/17/docker
    ports:
      - 5432:5432

  proxy:
    image: traefik
    command:
      # Providers
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.allowEmptyServices=true

      - --entrypoints.web.address=:80

      # Observability
      - --log.level=INFO
      - --accesslog=true
      - --metrics.prometheus=true
    ports:
      - ${HTTP_PUBLISH_PORT:-80}:80
      - ${HTTPS_PUBLISH_PORT:-443}:443
      - 8080:8080
    volumes:
      - cert-data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    userns_mode: host

volumes:
  odoo-filestore:
  db-data:
  cert-data:
